services:
  database:
    image: postgres:15-alpine
    container_name: greenlight_database
    restart: always
    tty: true
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .${APP_ENV}.env
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./db/seed/seed.sql:/home/seed.sql
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  database_test:
    image: postgres:15-alpine
    container_name: greenlight_database_test
    restart: always
    tty: true
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .${APP_ENV}.env
    volumes:
      - database_data_test:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}

  api:
    container_name: greenlight_api
    build:
      context: .
      dockerfile: ./dev.dockerfile
    ports:
      - 4000:4000
    env_file:
      - .${APP_ENV}.env
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_CONTAINER}:${DATABASE_PORT}/${DATABASE_NAME}?sslmode=disable
    volumes:
      - ./:/app
volumes:
  database_data:
  database_data_test:
