version: "3"

dotenv:
  - ".env"

tasks:
  migrate_up:
    cmds:
      - migrate -path ./migrations -database ${DATABASE_URL} -verbose up
    silent: true
  migrate_down:
    cmds:
      - migrate -path ./migrations -database ${DATABASE_URL} -verbose down
    silent: true
  dev:
    cmds:
      - CompileDaemon -build="go build -o ./bin/api ./cmd/api" -command="./bin/api -db-dsn=${DATABASE_URL} -smtp-host=${SMPT_HOST} -smtp-port=${SMPT_PORT} -smtp-username=${SMTP_USERNAME} -smtp-password=${SMTP_PASSWORD} -smtp-sender=${SMTP_SENDER} -cors-trusted-origins=${CORS_TRUSTED_ORIGINS}"
    silent: true
